### ISSUE TITLE
create ui for game timer countdown

### ISSUE THREAD

**Issue by okhaimie-dev** [realm-of-ra/mancala#106]

**Comment by ktarun1419** [comment]
can i work on this ?

**Comment by nemealfaro** [comment]
Hi @okhaimie-dev , I'm Nemesis Alfaro from Costa Rica, i'm a system engineer and web developer on CNFL Company.
I'm hard-working, constant and curious person
This would be my first contribution on the platform, in order to gain more knowledge and improve in the area.

If you need a figma design, I would like to help you, I have already used this tool in my work.

**Comment by Israelrex9** [comment]
Working on it @okhaimie-dev

**Comment by okhaimie-dev** [comment]
Thanks @Israelrex9 love this design.

**Comment by okhaimie-dev** [comment]
@ktarun1419 it is a somewhat small fix, do you think you'd be able to implement it tomorrow?

You just need to create a `timer-card.tsx` component and import it to the `game-play.tsx` page

**Comment by ktarun1419** [comment]
Yes for sure by tomorrow evening i will give you

**Comment by okhaimie-dev** [comment]
alright. i will assign you the task here too.

**Comment by Psalmuel01** [comment]
Can I hop on this if still not done?

**Comment by ktarun1419** [comment]
will raise PR today

**Comment by okhaimie-dev** [comment]
@ktarun1419 ODHack is over. We will handle this in-house

**Comment by ktarun1419** [comment]
ok so should i quit this issue? as the work is almost done

**Comment by od-hunter** [comment]
Hi @okhaimie-dev  , Is this still available? I’m ready to work on it ASAP!
