### ISSUE TITLE
frontend improvement: connect wallet component

### ISSUE THREAD

**Issue by Israelrex9** [realm-of-ra/mancala#96]
Description: Create a “Connect Wallet” button with a dropdown that matches the design in [figma](https://www.figma.com/design/6fQvKQWmxnt0XLUSjBjecj/MANCALA-Game-UI?node-id=1372-11495&m=dev)

This is the current look on production
![Screenshot 2024-06-19 at 1 02 40 AM](https://github.com/realm-of-ra/mancala/assets/46507005/143cbfe9-c5d7-4be1-976a-5ff84df3561c)

This is how it should look like as it is on figma
![Screenshot 2024-06-19 at 6 59 18 AM](https://github.com/realm-of-ra/mancala/assets/46507005/8fc83852-ea8a-4b43-a856-9d6726a6aa87)

Figma link; https://www.figma.com/design/6fQvKQWmxnt0XLUSjBjecj/MANCALA-Game-UI?node-id=1372-11495&m=dev

<img width="714" alt="Screenshot 2024-06-19 at 4 53 01 PM" src="https://github.com/realm-of-ra/mancala/assets/46507005/7ec92546-5eba-4170-9a93-cba9c36134a7">

	•	The connected wallet icon reveals where the "Braavos" wallet logo is displayed.
        •	Clicking anywhere on the button should open a modal showing options to connect a wallet.
	•	The dropdown menu should only appear when the (^) icon is clicked.
	•	Wallet disconnection can only be done using the button found within the dropdown.
	•	Note: The profile page has not been created yet.

**Comment by od-hunter** [comment]
Hi @Israelrex9 , Please can I be assigned this issue? I’m a Full-Stack Blockchain Developer and I believe I can solve this issue. Please give me the opportunity.

**Comment by okhaimie-dev** [comment]
@Israelrex9 

![CleanShot 2024-06-18 at 22 02 42](https://github.com/realm-of-ra/mancala/assets/57156589/42c1eb9a-fb84-4238-aadd-41c28b905a02)

I believe should use the wallet provider logo for this and not Starknet icon. I like the other part of the suggestion.

**Comment by Jemiiah** [comment]
@Israelrex9 i would love to work on this issue

**Comment by Israelrex9** [comment]
Updated the description, everyone.

✨ When applying for a task, please include a brief description of your experience and an estimated time frame for completion.

**Comment by Joy-Adah** [comment]
Hi @Israelrex9 my name is Joy and I am a frontend developer proficient with React, next js, shadcn, tailwind css. I'll have this task ready before close of business today.

**Comment by od-hunter** [comment]
As a UI/UX Designer, I have extensive experience in creating user-centered designs that enhance user experiences and meet business objectives. My expertise includes User Research, wire-framing and prototyping, Visual Design, Interaction Design and collaboration.

As a Full-Stack Blockchain Developer, I possess a robust skill set in both front-end and back-end development, My experience includes html, css, react, JavaScript Cairo ,TypeScript, rust and small knowledge on GO.

I’d have my PR ready in less than 24 hours once I’m assigned.

**Comment by okhaimie-dev** [comment]
> •	The connected wallet icon reveals where the "Braavos" wallet logo is displayed.
    •	Clicking anywhere on the button should open a modal showing options to connect a wallet.
•	The dropdown menu should only appear when the (^) icon is clicked.
•	Wallet disconnection can only be done using the button found within the dropdown.
•	Note: The profile page has not been created yet.


@Israelrex9 can you also include a screenshot of the drop down? This will be helpful for the developer to complete the task

**Comment by od-hunter** [comment]
Hello @Israelrex9 im waiting to be assigned by you please🙏🏾

**Comment by Oshioke-Salaki** [comment]
Hello i'd like to be assigned this

**Comment by Ugo-X** [comment]
Hi @Israelrex9 ,

I'm Ugo, a fullstack developer with a strong track record in OD hack projects (JavaScript, React, Node.js, Next.js, Three.js). I've been actively involved since Edition 2, contributing to various initiatives, and I'm excited to be part of Edition 5!

My extensive experience using OnlyDust (as reflected in my profile: https://app.onlydust.com/)) has given me a deep understanding of the platform. I'm eager to leverage this knowledge and my fullstack skills to tackle new challenges within this edition.

In particular, I'm interested in the dropdown button component development.  My experience with similar UI components and familiarity with the Figma design make me confident in delivering a pixel-perfect representation. I estimate the completion timeframe to be 1-2 days, depending on the specific requirements. I will proactively communicate any unforeseen delays.

I'm highly motivated and ready to contribute effectively. I'd happily take on this task if it's still available. Please let me know if you have any questions or require further information about my skills and experience.

Thanks.

**Comment by Ayoazeez26** [comment]
Hi @Israelrex9 I am a frontend developer with 6 years experience building applications and I would love to work on this issue
Here is my onlydust profile: https://app.onlydust.com/u/Ayoazeez26
Here is my github profile: https://github.com/Ayoazeez26
I would take 2 working days to deliver this task unfailingly

**Comment by Joshaw-k** [comment]
I would like to try this. This sounds interesting

**Comment by MariangelaNM** [comment]
ChatGPT
Certainly! Here's the text in English:

I'm excited to tackle my first issue here, leveraging substantial experience in frontend development. I intend to approach this challenge progressively and efficiently.

The process I'll follow will be structured to meet the project's specific requirements. Based on the provided details:

I will implement functionality so that clicking anywhere on the button opens a clear modal with options to connect a wallet.

I'll ensure the dropdown menu appears only when clicking the (^) icon, ensuring an intuitive and organized user experience.

For wallet disconnection, I'll enable this action exclusively through the button within the dropdown, adhering to specified guidelines.

It's worth noting that the profile page hasn't been created yet, and I'll factor this into future implementation considerations. I'm eager to contribute my technical skills and deliver a robust, well-integrated solution for this issue.

I'm ready to get started and committed to delivering high-quality results!

**Comment by okhaimie-dev** [comment]
@od-hunter I just assigned the task to you

**Comment by od-hunter** [comment]
@okhaimie-dev thank you

**Comment by okhaimie-dev** [comment]
here ser: https://t.me/+0UKU3P3Eh_s2NTRh

feel free to ask questions there

**Comment by xpanvictor** [comment]
@od-hunter we'll be working with you on this as I'm also working on refactoring. Will say hi on TG. Trying to minimize conflicts. 
First step, ensure separation of concerns. I also have some inputs on that, we'll discuss that soon

**Comment by okhaimie-dev** [comment]
@od-hunter are you still working on this, or should I reassign it to someone else

**Comment by od-hunter** [comment]
Hey @okhaimie-dev , yes I’m still working on it, I’ll send a PR before the end of today🙏🏾

**Comment by od-hunter** [comment]
@okhaimie-dev please review🙏🏾
